/* Input state machine: picking, object-plane dragging, orbit, pan and true two-pointer gestures. */
const pointers=new Map();let interaction=null;
function planeAt(x,y,height){const d=Luna.cam.ray(x,y);if(Math.abs(d[1])<.005)return null;const t=(height-Luna.cam.eye[1])/d[1];return t>.0?V.add(Luna.cam.eye,V.mul(d,t)):null}
function pointerDown(e){if(e.button>2||!Luna.gpu.ready)return;if(e.pointerType==='mouse'&&e.button===2)e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});e.currentTarget.setPointerCapture(e.pointerId);if(pointers.size===2){Luna.editor.commit();const p=[...pointers.values()];interaction={mode:'gesture',distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),mid:[(p[0].x+p[1].x)/2,(p[0].y+p[1].y)/2]};return}
const hit=Luna.scene.pick(e.clientX,e.clientY);Luna.cam.stop();interaction={mode:e.button===1||e.shiftKey?'pan':'orbit',startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,moved:false,hit,pointer:e.pointerId};
if(Luna.editor.open&&e.button===0&&!e.shiftKey&&hit.group){Luna.editor.select(hit.group.id,hit.object.slot);if(!hit.group.locked){interaction.mode='object';interaction.id=hit.group.id;interaction.offset=[...hit.group.offset];interaction.plane=hit.point[1];interaction.anchor=planeAt(e.clientX,e.clientY,hit.point[1]);}}
$('room').style.cursor=interaction.mode==='object'?'move':'grabbing';}
function pointerMove(e){if(!Luna.gpu.ready)return;if(!pointers.has(e.pointerId)){if(e.pointerType==='mouse'&&Luna.editor.open){const h=Luna.scene.pick(e.clientX,e.clientY);$('room').style.cursor=h.group&&!h.group.locked?'move':'grab'}return}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!interaction)return;if(pointers.size===2){const p=[...pointers.values()],distance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),mid=[(p[0].x+p[1].x)/2,(p[0].y+p[1].y)/2];if(interaction.mode==='gesture'&&distance>8&&interaction.distance>8){Luna.cam.zoom(Math.log(interaction.distance/distance)*1000);Luna.cam.pan(mid[0]-interaction.mid[0],mid[1]-interaction.mid[1]);interaction.distance=distance;interaction.mid=mid;}return}
if(interaction.mode==='gesture')return;const dx=e.clientX-interaction.x,dy=e.clientY-interaction.y;const moved=Math.hypot(e.clientX-interaction.startX,e.clientY-interaction.startY)>4;if(moved)interaction.moved=true;if(!interaction.moved)return;
if(interaction.mode==='object'){const g=Luna.scene.group(interaction.id),p=planeAt(e.clientX,e.clientY,interaction.plane);if(g&&p&&interaction.anchor){Luna.editor.begin();for(const i of [0,2]){const value=g.pivot[i]+interaction.offset[i]+p[i]-interaction.anchor[i];g.offset[i]=(Luna.editor.snap&&!e.altKey?Math.round(value/.05)*.05:value)-g.pivot[i]}constrain(g);Luna.scene.rebuild();Luna.editor.sync();Luna.gpu.invalidate()}}
else if(interaction.mode==='pan')Luna.cam.pan(dx,dy);else Luna.cam.orbit(dx,dy);interaction.x=e.clientX;interaction.y=e.clientY;}
function pointerUp(e){pointers.delete(e.pointerId);if(interaction&&interaction.pointer===e.pointerId&&!interaction.moved&&!Luna.editor.open&&e.type!=='pointercancel'){const hit=interaction.hit;if(hit?.object&&hit.group){if(hit.object.slot==='front'||hit.object.slot==='upper'){Luna.editor.transaction(()=>{const m=Luna.scene.surface(hit.group,hit.object.slot,hit.object.source);hit.group.overrides[hit.object.slot]={id:m.id==='sand'?'oak':'sand'};Luna.cam.stop()});Luna.hud.hint(hit.group.name+' · Oberfläche gewechselt.')}else if(hit.object.slot==='stone'&&['island','worktop'].includes(hit.group.kind))Luna.scene.togglePrice()}}
if(!pointers.size){Luna.editor.commit();interaction=null;$('room').style.cursor='grab';Luna.store.schedule()}}
$('room').addEventListener('pointerdown',pointerDown);$('room').addEventListener('pointermove',pointerMove);$('room').addEventListener('pointerup',pointerUp);$('room').addEventListener('pointercancel',pointerUp);$('room').addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))pointerUp({...e,type:'pointercancel',pointerId:e.pointerId})});$('room').addEventListener('contextmenu',e=>e.preventDefault());$('room').addEventListener('wheel',e=>{if(!Luna.gpu.ready)return;e.preventDefault();Luna.cam.zoom(e.deltaY);Luna.store.schedule()},{passive:false});
document.addEventListener('keydown',e=>{
const key=e.key.toLowerCase(),target=e.target;const form=target instanceof HTMLElement&&target.matches('input,select,textarea,[contenteditable=true]');
if(e.key==='Escape'&&$('confirm-reset').open)return;
if((e.metaKey||e.ctrlKey)&&key==='s'){if(form)return;e.preventDefault();$('project-save').click();return}
if((e.metaKey||e.ctrlKey)&&key==='z'){if(form)return;e.preventDefault();if(e.shiftKey)Luna.editor.redo();else Luna.editor.undo();return}
if(form&&!(target.type==='range'&&['f','e','c','escape'].includes(key)))return;
if(e.metaKey||e.ctrlKey||e.altKey&&!['arrowleft','arrowright','arrowup','arrowdown'].includes(key))return;
if(key==='f'){e.preventDefault();fullscreen()}else if(key==='e'){e.preventDefault();Luna.editor.toggle()}else if(key==='s'){e.preventDefault();Luna.gpu.snapshot()}else if(key==='c'){Luna.scene.ceo=!Luna.scene.ceo;Luna.hud.sync();Luna.gpu.invalidate()}else if(key==='p'){Luna.scene.togglePrice()}else if(key==='m'){Luna.scene.cycle()}else if(e.key==='Escape'){e.preventDefault();if(Luna.editor.open)Luna.editor.toggle(false);else Luna.cam.goto(5)}else if(e.code==='Space'){e.preventDefault();Luna.cam.toggle()}else if(/^[1-6]$/.test(key)){e.preventDefault();if(Luna.editor.open)Luna.editor.toggle(false);Luna.cam.goto(Number(key)-1)}else if(Luna.editor.open&&key==='r'){const g=Luna.scene.group(Luna.editor.selected);if(g&&!g.locked)Luna.editor.transaction(()=>{g.yaw=((g.yaw+Math.PI/12+Math.PI)%TAU)-Math.PI;constrain(g)})}
else if(Luna.editor.open&&['arrowleft','arrowright','arrowup','arrowdown'].includes(key)){e.preventDefault();const g=Luna.scene.group(Luna.editor.selected);if(g&&!g.locked){const step=e.altKey?.01:.05;Luna.editor.transaction(()=>{g.offset[key.includes('left')||key.includes('right')?0:2]+=key==='arrowleft'||key==='arrowup'?-step:step;constrain(g)})}}
else if(!Luna.editor.open&&['arrowleft','arrowright','arrowup','arrowdown'].includes(key)){e.preventDefault();const b=Luna.cam.basis(),d=V.norm([b.f[0],0,b.f[2]]),v=key==='arrowup'?V.mul(d,.15):key==='arrowdown'?V.mul(d,-.15):V.mul(b.r,key==='arrowleft'?-.15:.15);Luna.cam.eye=V.add(Luna.cam.eye,v);Luna.cam.to=V.add(Luna.cam.to,v);Luna.cam.stop();Luna.gpu.invalidate()}
});
addEventListener('resize',()=>{resizeStill();Luna.gpu.invalidate()});document.addEventListener('visibilitychange',()=>{lastFrame=performance.now();if(!document.hidden)Luna.gpu.invalidate()});reduced.addEventListener?.('change',e=>{if(e.matches){Luna.cam.playing=false;Luna.cam.transition=null;Luna.hud.sync()}});
Luna.cam.apply(0);
let startupNotice='';
if(!params.has('fresh')){try{const raw=localStorage.getItem(Luna.store.key);if(raw){const stored=JSON.parse(raw);if(stored.version===2){Luna.store.apply(stored);startupNotice='Ihr lokal gespeicherter Entwurf ist wieder da.';}else if(stored.version===1){Luna.scene.material=stored.material===1?1:0;Luna.scene.sun=Number.isFinite(stored.sun)?clamp(stored.sun):.7;Luna.cam.goto(Number.isInteger(stored.chapter)?stored.chapter:0,false);Luna.cam.playing=false;startupNotice='Bisherige Präsentation übernommen. Atelier ist bereit.'}else startupNotice='Der alte Speicherstand wurde nicht verändert. Atelier startet mit der Ausgangsküche.'}}catch{startupNotice='Lokaler Speicher ist nicht verfügbar oder ungültig. Ein Projekt-Export bleibt möglich.';$('save-state').textContent='Bitte exportieren · Speicher nicht verfügbar';$('save-state').classList.add('warning')}}
if(params.has('chapter'))Luna.cam.goto(clamp(Number(params.get('chapter'))-1,0,5),false);if(params.has('paused'))Luna.cam.playing=false;if(forcedFallback)Luna.cam.playing=false;
Luna.scene.ceo=false;Luna.scene.rebuild();resizeStill();Luna.hud.sync();Luna.editor.selected='island';Luna.editor.sync();
requestAnimationFrame(()=>{Luna.gpu.firstPaintMS=performance.now()});
Luna.gpu.init().then(()=>{if(params.has('edit'))Luna.editor.toggle(true);if(startupNotice)Luna.hud.hint(startupNotice)}).catch(err=>{if(!forcedFallback)Luna.gpu.errors.push(err.message);Luna.gpu.fallback(forcedFallback?'Canvas2D ausdrücklich gewählt.':err.message)});
Luna.gpu.invalidate();
Luna.qa={getState:()=>({version:Luna.version,backend:Luna.gpu.backend,adapter:Luna.gpu.adapter,errors:Luna.gpu.errors,samples:Luna.gpu.samples,firstImageMS:Luna.gpu.firstImageMS,firstGPUMS:Luna.gpu.firstGPUMS,scene:Luna.scene.bounds(),theme:Luna.scene.theme,selected:Luna.editor.selected,history:{undo:undoStack.length,redo:redoStack.length}}),setCenter:(id,x,y,z)=>{const g=Luna.scene.group(id);if(!g||g.locked)throw Error('Unknown editable group');Luna.editor.transaction(()=>{for(const [i,v]of [x,y,z].entries())if(v!==null)setCenter(g,i,v);constrain(g)})},center:id=>groupCenter(Luna.scene.group(id))};
