let hintTimer,selectedSlot='front';
Luna.hud.announce=t=>Luna.hud.hint(t);
Luna.hud.hint=t=>{$('hint').textContent=t;$('hint').classList.add('visible');clearTimeout(hintTimer);hintTimer=setTimeout(()=>$('hint').classList.remove('visible'),5000)};
for(let i=0;i<6;i++){const b=document.createElement('button');b.innerHTML='<small>0'+(i+1)+'</small>'+cs[i].name;b.dataset.chapter=i;b.setAttribute('aria-label','Kapitel '+(i+1)+': '+cs[i].name);b.onclick=()=>{if(Luna.editor.open)Luna.editor.toggle(false);Luna.cam.goto(i)};$('chapters').append(b);const fb=document.createElement('button');fb.setAttribute('aria-label','Standbild '+cs[i].name);fb.innerHTML='<canvas width="240" height="135"></canvas>';fb.onclick=()=>Luna.cam.goto(i,false);$('filmstrip').append(fb)}
const chapterButtons=[...document.querySelectorAll('[data-chapter]')];
Luna.hud.sync=()=>{const i=Luna.cam.chapter;document.body.classList.toggle('stille',i===5&&!Luna.scene.ceo&&!Luna.editor.open);chapterButtons.forEach((b,j)=>{b.setAttribute('aria-current',String(i===j));b.style.setProperty('--progress',Luna.cam.playing?clamp((Luna.cam.time-i*8)/8):1)});[...$('filmstrip').children].forEach((b,j)=>b.setAttribute('aria-current',String(i===j)));$('play').textContent=Luna.cam.playing?'Ⅱ':'▷';$('play').setAttribute('aria-label',Luna.cam.playing?'Film pausieren':'Film abspielen');$('sun').value=Math.round(Luna.scene.sun*100);$('room').setAttribute('aria-label','Küche der Familie Berger. '+(Luna.editor.open?'Live-Gestaltung: Wählen und ziehen Sie Möbel. Rechte Maustaste: Ansicht drehen.':'Ziehen Sie zum Umsehen. Front berühren: Eiche oder Sandlack. Arbeitsplatte berühren: Demo-Preis. E: Raum gestalten.'))};
Luna.hud.draw=()=>{const c=$('inscriptions'),w=innerWidth,h=innerHeight,ratio=Math.min(devicePixelRatio,2);if(c.width!==Math.round(w*ratio)||c.height!==Math.round(h*ratio)){c.width=Math.round(w*ratio);c.height=Math.round(h*ratio)}const g=c.getContext('2d');g.setTransform(ratio,0,0,ratio,0,0);g.clearRect(0,0,w,h);
const silent=Luna.cam.chapter===5&&!Luna.scene.ceo&&!Luna.editor.open;
const a=Luna.cam.project([-3.135,.692,-.78]),b=Luna.cam.project([-3.135,.692,1.54]);const on=Luna.gpu.ready&&!silent&&a.z>.1&&b.z>.1&&a.x>-100&&b.x<w+100;
$('sun').style.display=on?'':'none';if(on){g.strokeStyle='rgba(226,231,220,.48)';g.lineWidth=.7;g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke();const p={x:mix(a.x,b.x,Luna.scene.sun),y:mix(a.y,b.y,Luna.scene.sun)};g.beginPath();g.arc(p.x,p.y,2.6,0,TAU);g.fillStyle='#e5dfcb';g.fill();g.fillStyle='rgba(233,229,213,.62)';g.font='8px Segoe UI,Arial';g.fillText(Luna.scene.sun<.4?'MORGENLICHT':'ABENDLICHT',a.x,a.y-9);const el=$('sun');el.style.left=a.x+'px';el.style.top=a.y-12+'px';el.style.width=Math.hypot(b.x-a.x,b.y-a.y)+'px';el.style.transform='rotate('+Math.atan2(b.y-a.y,b.x-a.x)+'rad)'}
const sel=Luna.editor.open&&Luna.scene.group(Luna.editor.selected);$('world-label').style.display='none';if(sel&&!sel.locked&&!sel.hidden){const bounds=sel.bounds,q=Q.axis([0,1,0],sel.yaw),origin=V.add(sel.pivot,sel.offset);const project=(x,y,z)=>Luna.cam.project(V.add(origin,Q.rotate(q,[x*sel.scale[0],y*sel.scale[1],z*sel.scale[2]])));const corners=[[bounds.lo[0],bounds.lo[2]],[bounds.hi[0],bounds.lo[2]],[bounds.hi[0],bounds.hi[2]],[bounds.lo[0],bounds.hi[2]]].map(p=>project(p[0],.01/sel.scale[1]-origin[1]/sel.scale[1],p[1]));if(corners.every(p=>p.z>.01)){g.save();g.setLineDash([5,4]);g.lineWidth=.85;g.strokeStyle='rgba(157,211,237,.75)';g.beginPath();corners.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath();g.stroke();g.restore();for(const p of corners){g.fillStyle='rgba(182,219,231,.8)';g.fillRect(p.x-1.5,p.y-1.5,3,3)}}
const center=V.mul(V.add(bounds.lo,bounds.hi),.5);const label=project(center[0],bounds.hi[1]+.15,center[2]);const editorLeft=$('editor').getBoundingClientRect().left;if(label.z>.1&&label.x>16&&label.x<Math.min(w-170,editorLeft-170)&&label.y>10&&label.y<h-130){$('world-label').style.display='block';$('world-label').style.left=label.x+'px';$('world-label').style.top=label.y+'px';$('object-label').textContent=sel.name;$('object-dim').textContent=bounds.size.map((v,i)=>Math.round(v*sel.scale[i]*1000)).join(' × ')+' mm'}
}
};
function groupCenter(g){const p=V.mul(V.add(g.bounds.lo,g.bounds.hi),.5);return V.add(V.add(g.pivot,g.offset),Q.rotate(Q.axis([0,1,0],g.yaw),p.map((v,i)=>v*g.scale[i])))}
function setCenter(g,axis,v){const c=groupCenter(g);g.offset[axis]+=v-c[axis]}
function constrain(g){const bounds=g.bounds,q=Q.axis([0,1,0],g.yaw);const c=groupCenter(g),half=bounds.size.map((v,i)=>v*g.scale[i]/2),r=Math.abs(Math.cos(g.yaw)),s=Math.abs(Math.sin(g.yaw)),hx=r*half[0]+s*half[2],hz=s*half[0]+r*half[2];setCenter(g,0,clamp(c[0],-3.23+hx,4.37-hx));setCenter(g,2,clamp(c[2],-2.84+hz,6.5-hz));const bottom=g.pivot[1]+g.offset[1]+bounds.lo[1]*g.scale[1],top=g.pivot[1]+g.offset[1]+bounds.hi[1]*g.scale[1];if(bottom<.002)g.offset[1]+=.002-bottom;if(top>3.25)g.offset[1]-=top-3.25;}
Luna.editor.openTab=tab=>{Luna.editor.tab=tab;for(const t of ['room','object','light']){$('tab-'+t).setAttribute('aria-selected',String(tab===t));$('tab-'+t).tabIndex=tab===t?0:-1;$('pane-'+t).hidden=tab!==t}$('editor-body').scrollTop=0};
Luna.editor.toggle=force=>{const open=force===undefined?!Luna.editor.open:force;if(open&&!Luna.gpu.ready){Luna.hud.hint('Live-Gestaltung benötigt WebGPU. Die Standbilder bleiben verfügbar.');return}Luna.editor.open=open;$('editor').hidden=!open;document.body.classList.toggle('editing',open);$('edit-toggle').setAttribute('aria-expanded',String(open));if(open){Luna.cam.stop();Luna.editor.selected??='island';Luna.editor.sync();Luna.hud.hint('Wählen Sie ein Möbel und ziehen Sie es. Rechte Maustaste: umsehen. E: zurück zum Raum.')}else{$('world-label').style.display='none';Luna.editor.commit();$('edit-toggle').focus({preventScroll:true})}Luna.hud.sync();Luna.gpu.invalidate()};
Luna.editor.select=(id,slot)=>{const sel=Luna.scene.group(id);if(!sel||sel.hidden)return;Luna.editor.selected=id;const slots=[...new Set(sel.parts.map(p=>p.slot))].filter(s=>s!=='fixed');Luna.editor.surface=slots.includes(slot)?slot:slots[0]||'front';Luna.editor.openTab('object');Luna.editor.sync();Luna.gpu.invalidate()};
Luna.editor.syncHistory=()=>{$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length};
Luna.editor.syncLight=()=>{const s=Luna.scene;for(const [id,value] of [['daylight',Math.round(s.sun*100)],['kelvin',s.kelvin],['light-power',Math.round(s.power*100)],['exposure',Math.round(s.exposure*10)]])if(document.activeElement!==$(id))$(id).value=value;$('daylight-value').textContent=s.sun<.3?'Morgen':s.sun<.68?'Nachmittag':'Abend';$('kelvin-value').textContent=s.kelvin.toLocaleString('de-AT')+' K';$('light-power-value').textContent=Math.round(s.power*100)+' %';$('exposure-value').textContent=s.exposure.toLocaleString('de-AT',{minimumFractionDigits:1,maximumFractionDigits:1})+' EV';$('strip-toggle').checked=s.strip;$('quality').value=s.quality;document.querySelectorAll('[data-light]').forEach(b=>b.setAttribute('aria-pressed',String(Math.abs(Number(b.dataset.light)-s.sun)<.04)))};
Luna.editor.sync=()=>{
Luna.editor.syncHistory();Luna.editor.syncLight();$('snap-toggle').checked=Luna.editor.snap;
document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(Luna.scene.theme===b.dataset.theme)));
const select=$('object-select'),existing=[...select.options].map(x=>x.value).join('|'),visible=groups.filter(g=>!g.hidden);if(existing!==visible.map(g=>g.id).join('|')){select.replaceChildren(...visible.map(g=>{const opt=document.createElement('option');opt.value=g.id;opt.textContent=g.name;return opt}))}
const sel=Luna.scene.group(Luna.editor.selected);if(!sel)return;select.value=sel.id;$('selection-help').textContent=sel.locked?'Architektur bleibt fix. Farbe, Material und Glanzgrad ändern Sie hier.':'Ziehen Sie das Element direkt im Raum. Positionen bezeichnen den Mittelpunkt.';$('transform-controls').hidden=sel.locked;
const center=groupCenter(sel);for(const [i,axis] of ['x','y','z'].entries()){if(document.activeElement!==$('pos-'+axis))$('pos-'+axis).value=Math.round(center[i]*1000);if(document.activeElement!==$('size-'+axis))$('size-'+axis).value=Math.round(sel.bounds.size[i]*sel.scale[i]*1000)}
if(document.activeElement!==$('rotation'))$('rotation').value=Math.round(sel.yaw*180/Math.PI);$('rotation-value').textContent=Math.round(sel.yaw*180/Math.PI)+'°';
const slots=[...new Set(sel.parts.map(p=>p.slot))].filter(s=>s!=='fixed');if(!slots.includes(Luna.editor.surface))Luna.editor.surface=slots[0]||'front';const surface=$('surface-select');surface.replaceChildren(...slots.map(slot=>{const opt=document.createElement('option');opt.value=slot;opt.textContent=slotNames[slot]||slot;return opt}));surface.value=Luna.editor.surface;
const example=sel.parts.find(p=>p.slot===Luna.editor.surface),finish=Luna.scene.surface(sel,Luna.editor.surface,example);document.querySelectorAll('[data-material]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.material===finish.id)));
if(document.activeElement!==$('surface-color'))$('surface-color').value=finish.color;if(document.activeElement!==$('roughness'))$('roughness').value=Math.round((1-finish.rough)*100);$('roughness-value').textContent=finish.rough>.65?'Matt':finish.rough>.34?'Seidenmatt':'Glänzend';if(document.activeElement!==$('texture-scale'))$('texture-scale').value=Math.round((finish.scale||1)*100);$('texture-scale-value').textContent=Math.round((finish.scale||1)*100)+' %';$('duplicate-object').disabled=sel.locked;$('delete-object').disabled=sel.locked;$('texture-note').textContent=Luna.scene.customImage?'Lokal eingebettet: '+Luna.scene.customName+'. Eine neue Datei ersetzt diese eigene Textur im Entwurf.':'PNG, JPG oder WebP bis 8 MB. Das Bild wird lokal eingebettet, nicht hochgeladen.';
};
for(const t of themes){const b=document.createElement('button');b.className='theme-card';b.dataset.theme=t.id;b.setAttribute('aria-label','Thema '+t.name);b.setAttribute('aria-pressed','false');const p=document.createElement('span');p.className='theme-preview';for(const col of t.swatches){const i=document.createElement('i');i.style.backgroundColor=col;p.append(i)}const name=document.createElement('b');name.textContent=t.name;const desc=document.createElement('small');desc.textContent=t.desc;b.append(p,name,desc);b.onclick=()=>Luna.theme.apply(t.id);$('themes').append(b)}
for(const m of materials){const b=document.createElement('button');b.className='material';b.dataset.material=m.id;b.title=m.name;b.setAttribute('aria-label','Material '+m.name);b.setAttribute('aria-pressed','false');const sw=document.createElement('span');sw.className='swatch';sw.style.backgroundColor=m.color;const label=document.createElement('span');label.textContent=m.name;b.append(sw,label);b.onclick=()=>{if(m.id==='custom'&&!Luna.scene.customImage){$('texture-file').click();return}const g=Luna.scene.group(Luna.editor.selected);if(!g)return;Luna.editor.transaction(()=>{g.overrides[Luna.editor.surface]={id:m.id};Luna.cam.stop()});};$('materials').append(b)}
Luna.editor.materialThumbs=()=>{document.querySelectorAll('[data-material]').forEach(b=>{const m=mat(b.dataset.material),s=b.querySelector('.swatch');if(m.tex>0&&textureCanvases[m.tex]){s.style.backgroundImage='url("'+textureCanvases[m.tex].toDataURL('image/webp',.35)+'")';s.style.backgroundBlendMode='multiply'}})};
function changeSurface(values){const g=Luna.scene.group(Luna.editor.selected);if(!g)return;const slot=Luna.editor.surface,example=g.parts.find(p=>p.slot===slot),current=Luna.scene.surface(g,slot,example);g.overrides[slot]={id:current.id,...g.overrides[slot],...values};Luna.scene.rebuild();Luna.editor.sync();Luna.gpu.invalidate()}
$('edit-toggle').onclick=()=>Luna.editor.toggle();$('edit-close').onclick=()=>Luna.editor.toggle(false);$('play').onclick=Luna.cam.toggle;$('object-select').onchange=e=>Luna.editor.select(e.target.value);$('surface-select').onchange=e=>{Luna.editor.surface=e.target.value;Luna.editor.sync()};
document.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>Luna.editor.openTab(b.dataset.tab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=['room','object','light'],i=tabs.indexOf(b.dataset.tab),next=tabs[(i+(e.key==='ArrowRight'?1:2))%3];Luna.editor.openTab(next);$('tab-'+next).focus()}}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>Luna.cam.view(b.dataset.view));$('snap-toggle').onchange=e=>Luna.editor.snap=e.target.checked;
for(const [index,axis] of ['x','y','z'].entries()){
$('pos-'+axis).onchange=e=>{const sel=Luna.scene.group(Luna.editor.selected),v=parseFloat(e.target.value);if(!sel||!Number.isFinite(v)||Math.abs(v)>10000){Luna.hud.hint('Bitte geben Sie eine gültige Position in mm ein.');e.target.blur();Luna.editor.sync();return}Luna.editor.transaction(()=>{setCenter(sel,index,v/1000);constrain(sel);Luna.cam.stop()});e.target.value=Math.round(groupCenter(sel)[index]*1000)};
$('size-'+axis).onchange=e=>{const sel=Luna.scene.group(Luna.editor.selected),v=parseFloat(e.target.value);if(!sel||!Number.isFinite(v)||v<10||v>8000){Luna.hud.hint('Bitte geben Sie eine gültige Abmessung in mm ein.');e.target.blur();Luna.editor.sync();return}Luna.editor.transaction(()=>{sel.scale[index]=clamp(v/1000/sel.bounds.size[index],.15,3);constrain(sel);Luna.cam.stop()});e.target.value=Math.round(sel.bounds.size[index]*sel.scale[index]*1000)};
}
function bindRange(id,fn){const e=$(id);e.addEventListener('pointerdown',Luna.editor.begin);e.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(event.key))Luna.editor.begin()});e.addEventListener('input',()=>{Luna.editor.begin();Luna.cam.stop();fn(Number(e.value));Luna.editor.syncLight();Luna.hud.sync();Luna.gpu.invalidate()});e.addEventListener('change',()=>{Luna.editor.commit();Luna.editor.sync()});e.addEventListener('blur',Luna.editor.commit)}
bindRange('rotation',v=>{const g=Luna.scene.group(Luna.editor.selected);if(!g||g.locked)return;g.yaw=v*Math.PI/180;constrain(g);Luna.scene.rebuild();$('rotation-value').textContent=v+'°'});
bindRange('roughness',v=>changeSurface({rough:clamp(1-v/100,.05,.95)}));bindRange('texture-scale',v=>changeSurface({scale:v/100}));bindRange('daylight',v=>Luna.scene.sun=v/100);bindRange('sun',v=>Luna.scene.sun=v/100);bindRange('kelvin',v=>Luna.scene.kelvin=v);bindRange('light-power',v=>Luna.scene.power=v/100);bindRange('exposure',v=>Luna.scene.exposure=v/10);
$('surface-color').addEventListener('input',e=>{Luna.editor.begin();changeSurface({color:e.target.value});Luna.cam.stop()});$('surface-color').addEventListener('change',()=>{Luna.editor.commit();Luna.editor.sync()});$('surface-clear').onclick=()=>{const g=Luna.scene.group(Luna.editor.selected);if(g)Luna.editor.transaction(()=>{delete g.overrides[Luna.editor.surface];Luna.scene.material=0})};
$('strip-toggle').onchange=e=>Luna.editor.transaction(()=>Luna.scene.strip=e.target.checked);$('quality').onchange=e=>{Luna.scene.quality=e.target.value;Luna.store.schedule();Luna.gpu.invalidate()};document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>Luna.editor.transaction(()=>{Luna.scene.sun=Number(b.dataset.light);Luna.cam.stop()}));
$('undo').onclick=Luna.editor.undo;$('redo').onclick=Luna.editor.redo;
$('duplicate-object').onclick=()=>{const source=Luna.scene.group(Luna.editor.selected);if(!source||source.locked)return;if(groups.filter(g=>!g.locked).length>=64){Luna.hud.hint('Maximal 64 Elemente pro Entwurf. Entfernen Sie nicht benötigte Kopien.');return}Luna.editor.transaction(()=>{const g=clone(source);g.id=(source.template||source.id)+'-copy-'+Date.now().toString(36);g.template=source.template||source.id;g.name=source.name.replace(/ · Kopie$/,'')+' · Kopie';g.offset[0]+=.32;g.offset[2]+=.45;constrain(g);groups.push(g);Luna.editor.selected=g.id});Luna.hud.hint('Kopie hinzugefügt. Ziehen Sie sie an ihren Platz.')};
$('delete-object').onclick=()=>{const g=Luna.scene.group(Luna.editor.selected);if(!g||g.locked)return;Luna.editor.transaction(()=>{g.hidden=true;Luna.editor.selected=groups.find(x=>!x.hidden&&!x.locked)?.id||'walls'});Luna.hud.hint('Element entfernt. Rückgängig stellt es wieder her.')};
$('reset-room').onclick=()=>$('confirm-reset').showModal();$('reset-cancel').onclick=()=>$('confirm-reset').close();$('reset-confirm').onclick=()=>{$('confirm-reset').close();Luna.editor.transaction(()=>{groups.splice(0,groups.length,...clone(factoryGroups));for(const g of groups)g.bounds=Luna.scene.getBounds(g);Object.assign(Luna.scene,clone(factoryScene));Luna.scene.customImage=null;Luna.scene.customName='';Luna.scene.price=false;Luna.scene.ceo=false;Luna.editor.selected='island';Luna.cam.view('wide')});Luna.gpu.loadCustom()};
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
$('project-save').onclick=()=>{Luna.editor.commit();download(new Blob([JSON.stringify(Luna.store.document(),null,2)],{type:'application/json'}),'LUNA-Berger-'+Luna.scene.theme+'.json');Luna.hud.hint('Entwurf exportiert. Die Datei enthält Ihre Möbel, Oberflächen, Beleuchtung und Kamera.')};$('project-load').onclick=()=>$('project-file').click();
$('project-file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2500000)throw Error('Projektdatei zu groß. Maximal 2,5 MB.');const data=Luna.store.validate(JSON.parse(await file.text()));if(data.customImage){const image=new Image();image.src=data.customImage;await image.decode();if(image.naturalWidth>4096||image.naturalHeight>4096)throw Error('Eingebettete Textur zu groß.')}Luna.editor.begin();Luna.store.apply(data);await Luna.gpu.loadCustom();Luna.editor.commit();Luna.editor.sync();Luna.hud.hint('Entwurf geöffnet. Alles bleibt lokal.')}catch(err){Luna.hud.hint('Projekt nicht geändert: '+err.message)}};
$('texture-import').onclick=()=>$('texture-file').click();$('texture-file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('Bitte wählen Sie PNG, JPG oder WebP bis 8 MB.');const url=URL.createObjectURL(file);let image;try{image=new Image();image.src=url;await image.decode();if(image.naturalWidth>16384||image.naturalHeight>16384)throw Error('Bildabmessungen zu groß.');}finally{URL.revokeObjectURL(url)}const c=document.createElement('canvas');c.width=c.height=512;c.getContext('2d').drawImage(image,0,0,512,512);Luna.editor.begin();Luna.scene.customImage=c.toDataURL('image/jpeg',.90);Luna.scene.customName=file.name.slice(0,100);const g=Luna.scene.group(Luna.editor.selected);g.overrides[Luna.editor.surface]={id:'custom'};await Luna.gpu.loadCustom();Luna.scene.rebuild();Luna.editor.commit();Luna.editor.sync();Luna.hud.hint('Eigene Textur angewendet und lokal eingebettet.')}catch(err){Luna.hud.hint('Textur nicht geändert: '+err.message)}};
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{Luna.hud.hint('Vollbild wurde vom Browser nicht freigegeben.')}}
$('fullscreen-button').onclick=fullscreen;$('film-button').onclick=()=>{Luna.cam.time=0;Luna.cam.chapter=0;Luna.cam.playing=false;Luna.cam.toggle()};
let capturing=false;
Luna.gpu.snapshot=async()=>{if(capturing)return;capturing=true;const wasPlaying=Luna.cam.playing,selected=Luna.editor.selected;Luna.cam.playing=false;const button=$('snapshot-button');button.disabled=true;Luna.hud.hint('Standbild wird in 1920 × 1080 entwickelt …');try{const c=document.createElement('canvas');c.width=1920;c.height=1080;const g=c.getContext('2d');if(Luna.gpu.ready){const editing=Luna.editor.open;Luna.editor.open=false;try{const pixels=await Luna.gpu.readPixels(1920,1080,48);g.putImageData(pixels,0,0)}finally{Luna.editor.open=editing}}else Luna.gpu.drawStill(c);const period=Luna.scene.sun<.35?'Morgen':Luna.scene.sun<.65?'Nachmittag':'Abend';g.fillStyle='rgba(13,24,31,.65)';g.fillRect(0,1036,1920,44);g.font='11px Segoe UI,Arial';g.fillStyle='#dfdace';g.fillText('STAGE / Berger / '+period,32,1063);g.textAlign='right';g.fillText('EDV Hausleitner · LUNA STAGE'+(Luna.gpu.ready?'':' · Standbild der Ausgangsküche'),1888,1063);const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('PNG konnte nicht erstellt werden.');download(blob,'STAGE-Berger-'+period+'.png');Luna.gpu.lastSnapshot={width:1920,height:1080,bytes:blob.size,type:blob.type};Luna.hud.hint('Standbild gespeichert. Ihre Ansicht bleibt unverändert.')}catch(err){Luna.hud.hint('Standbild nicht gespeichert: '+err.message)}finally{Luna.cam.playing=wasPlaying;Luna.editor.selected=selected;capturing=false;button.disabled=false;Luna.hud.sync();Luna.gpu.invalidate()}};
$('snapshot-button').onclick=Luna.gpu.snapshot;$('photo-button').onclick=Luna.gpu.snapshot;
