/* Native raster engine: reusable unit geometry, GPU affine transforms and two depth maps. */
let roomDepth,meshBuffer,meshVertices=0,meshSignature='',skyPipeline,shadowPipeline,shadowMap,shadowUniforms=[],shadowBindGroups=[],shadowInfoBuffer,shadowSignature='';
const unitMeshes=new Map();
function unitMesh(o){
 const key=[o.type,...o.dim,o.bevel].join(',');if(unitMeshes.has(key))return unitMeshes.get(key);const out=[];
 const tri=(a,b,c,na,nb,nc)=>{if(V.dot(V.cross(V.sub(b,a),V.sub(c,a)),V.add(V.add(na,nb),nc))<0){[b,c]=[c,b];[nb,nc]=[nc,nb]}out.push([...a,...na],[...b,...nb],[...c,...nc]);};
 if(o.type===0){const bevel=Math.min(o.bevel,...o.dim.map(v=>v*.24));const radius=o.dim.map(v=>bevel/v);const rounded=q=>{const base=q.map((v,i)=>clamp(v,-1+radius[i],1-radius[i]));const delta=q.map((v,i)=>(v-base[i])*o.dim[i]);const norm=V.norm(delta);return {p:base.map((v,i)=>v+norm[i]*bevel/o.dim[i]),n:norm.map((v,i)=>v*o.dim[i])}};
  for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const a=(axis+1)%3,b=(axis+2)%3;const aa=bevel>0?[-1,-1+radius[a],1-radius[a],1]:[-1,1],bb=bevel>0?[-1,-1+radius[b],1-radius[b],1]:[-1,1];const point=(x,y)=>{let q=[0,0,0];q[axis]=sign;q[a]=x;q[b]=y;if(bevel>0)return rounded(q);const n=[0,0,0];n[axis]=sign;return {p:q,n}};
   for(let i=0;i<aa.length-1;i++)for(let j=0;j<bb.length-1;j++){const v=[point(aa[i],bb[j]),point(aa[i+1],bb[j]),point(aa[i+1],bb[j+1]),point(aa[i],bb[j+1])];tri(v[0].p,v[1].p,v[2].p,v[0].n,v[1].n,v[2].n);tri(v[0].p,v[2].p,v[3].p,v[0].n,v[2].n,v[3].n)}}
 }else if(o.type===1){const lat=o.dim[1]<.02?4:10,lon=o.dim[1]<.02?8:18;const point=(a,b)=>[Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)];for(let i=0;i<lat;i++)for(let j=0;j<lon;j++){const a=point(i*Math.PI/lat,j*TAU/lon),b=point((i+1)*Math.PI/lat,j*TAU/lon),c=point((i+1)*Math.PI/lat,(j+1)*TAU/lon),d=point(i*Math.PI/lat,(j+1)*TAU/lon);tri(a,b,c,a,b,c);tri(a,c,d,a,c,d)}}
 else{const count=o.dim[0]>.1?28:14;for(let i=0;i<count;i++){const t=i*TAU/count,s=(i+1)*TAU/count,a=[Math.cos(t),-1,Math.sin(t)],b=[Math.cos(s),-1,Math.sin(s)],c=[Math.cos(s),1,Math.sin(s)],d=[Math.cos(t),1,Math.sin(t)],na=[a[0],0,a[2]],nb=[b[0],0,b[2]];tri(a,b,c,na,nb,nb);tri(a,c,d,na,nb,na);tri([0,-1,0],b,a,[0,-1,0],[0,-1,0],[0,-1,0]);tri([0,1,0],d,c,[0,1,0],[0,1,0],[0,1,0]);}}
 unitMeshes.set(key,out);return out;
}
function uploadRasterScene(){
 if(uploadRevision===Luna.scene.revision)return;const objects=Luna.scene.objects;
 const data=new Float32Array(objects.flatMap(o=>[...o.c,o.type,...o.rows[0],o.ext[0],...o.rows[1],o.ext[1],...o.rows[2],o.ext[2],...o.color,o.m.rough,o.m.tex,o.m.metal,o.m.emission||0,o.m.scale||1,o.flag,o.gi,o.id,o.bevel,...o.dim,o.shadow]));device.queue.writeBuffer(objectBuffer,0,data);
 device.queue.writeBuffer(lightBuffer,0,new Float32Array(lightData.flatMap(l=>[...l.a,l.power,...l.b,l.strip?1:0])));
 const signature=objects.map(o=>[o.type,...o.dim,o.bevel,o.id,o.gi].join(',')).join('|');if(signature!==meshSignature){const pieces=objects.map(unitMesh);meshVertices=pieces.reduce((n,p)=>n+p.length,0);const floats=new Float32Array(meshVertices*7),bits=new Uint32Array(floats.buffer);let k=0;pieces.forEach((vertices,id)=>{for(const vertex of vertices){floats.set(vertex,k);bits[k+6]=id;k+=7}});meshBuffer?.destroy();meshBuffer=device.createBuffer({size:floats.byteLength,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(meshBuffer,0,floats);meshSignature=signature;}
 uploadRevision=Luna.scene.revision;Luna.gpu.objectCount=objects.length;Luna.gpu.vertexCount=meshVertices;Luna.gpu.lightCount=lightData.length;
}
function shadowValues(origin,target,halfW,halfH,far){const f=V.norm(V.sub(target,origin)),right=V.norm(V.cross(f,Math.abs(f[1])>.96?[0,0,1]:[0,1,0])),up=V.cross(right,f);return [...origin,halfW,...right,halfH,...up,far,...f,0]}
function renderShadowMaps(encoder){const s=Luna.scene;const key=[s.revision,s.sun].join('|');if(key===shadowSignature)return;const direction=V.norm([-1,mix(.85,.24,s.sun),mix(-.34,.25,s.sun)]);const target=[.4,1.0,.1],sunOrigin=V.add(target,V.mul(direction,9));const main=lightData.find(l=>!l.strip);const lamp=main?V.mul(V.add(main.a,main.b),.5):[.05,2.27,.42];lamp[1]-=.065;
 const values=[shadowValues(sunOrigin,target,6.7,6.7,20),shadowValues(lamp,[lamp[0],-.3,lamp[2]],4.1,4.8,8)];device.queue.writeBuffer(shadowInfoBuffer,0,new Float32Array(values.flat()));
 for(let i=0;i<2;i++){device.queue.writeBuffer(shadowUniforms[i],0,new Float32Array(values[i]));const pass=encoder.beginRenderPass({colorAttachments:[],depthStencilAttachment:{view:shadowMap.createView({dimension:'2d',baseArrayLayer:i,arrayLayerCount:1}),depthLoadOp:'clear',depthClearValue:1,depthStoreOp:'store'}});pass.setPipeline(shadowPipeline);pass.setBindGroup(0,shadowBindGroups[i]);pass.setVertexBuffer(0,meshBuffer);pass.draw(meshVertices);pass.end();}shadowSignature=key;
}
Luna.gpu.render=(width,height)=>{
 if(!Luna.gpu.ready)return;uploadRasterScene();const canvas=$('room');let w=width,h=height;
 if(!w||!h){const moving=Luna.cam.playing||!!Luna.cam.transition||performance.now()-settleAt<150;let ratio=Math.min(devicePixelRatio,1.15,1920/innerWidth);if(moving)ratio=Math.min(.70,1160/innerWidth);w=Math.max(2,Math.round(innerWidth*ratio));h=Math.max(2,Math.round(innerHeight*ratio));}
 if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;
 if(historySize!==w+'x'+h){histories.forEach(t=>t.destroy());roomDepth?.destroy();histories=[0,1].map(()=>device.createTexture({size:[w,h],format:'rgba16float',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.RENDER_ATTACHMENT}));roomDepth=device.createTexture({size:[w,h],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});groupsGPU=histories.map(t=>device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[...staticEntries,{binding:4,resource:t.createView()}]}));presentGroups=histories.map(t=>device.createBindGroup({layout:presentPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:t.createView()}]}));historySize=w+'x'+h;sampleCount=0;stateKey='';}
 const b=Luna.cam.basis(),s=Luna.scene,selected=Luna.editor.open?groups.findIndex(g=>g.id===Luna.editor.selected):-1;const key=[w,h,...Luna.cam.eye,...Luna.cam.to,Luna.cam.fov,s.sun,s.kelvin,s.power,s.exposure,s.strip,s.price,s.ceo,s.revision,selected,Luna.editor.open].join('|');if(key!==stateKey){sampleCount=0;stateKey=key;}const read=sampleCount%2,write=1-read;
 device.queue.writeBuffer(uniform,0,new Float32Array([...Luna.cam.eye,b.tan*w/h,...b.f,b.tan,...b.r,0,...b.u,0,w,h,s.sun,s.material,s.price?1:0,s.ceo?1:0,Luna.cam.chapter,sampleCount,...kelvinRGB(s.kelvin),s.power,s.exposure,s.strip?1:0,0,Luna.editor.open?1:0,lightData.length,selected,Luna.scene.objects.length,bvhNodes.length]));
 const encoder=device.createCommandEncoder();renderShadowMaps(encoder);const pass=encoder.beginRenderPass({colorAttachments:[{view:histories[write].createView(),loadOp:'clear',storeOp:'store'}],depthStencilAttachment:{view:roomDepth.createView(),depthLoadOp:'clear',depthClearValue:1,depthStoreOp:'discard'}});pass.setBindGroup(0,groupsGPU[read]);pass.setPipeline(skyPipeline);pass.draw(3);pass.setPipeline(pipeline);pass.setVertexBuffer(0,meshBuffer);pass.draw(meshVertices);pass.end();lastSurface=context.getCurrentTexture();const display=encoder.beginRenderPass({colorAttachments:[{view:lastSurface.createView(),loadOp:'clear',storeOp:'store'}]});display.setPipeline(presentPipeline);display.setBindGroup(0,presentGroups[write]);display.draw(3);display.end();const started=performance.now();device.queue.submit([encoder.finish()]);sampleCount++;Luna.gpu.samples=sampleCount;Luna.gpu.frames++;gpuInFlight=true;Luna.gpu.pending=device.queue.onSubmittedWorkDone().then(()=>{gpuInFlight=false;Luna.gpu.lastFrameMS=performance.now()-started;});
};
Luna.gpu.init=async()=>{
 await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,0)));
 if(forcedFallback)throw Error('Canvas2D ausdrücklich gewählt');if(!navigator.gpu)throw Error('Dieser Browser stellt WebGPU nicht bereit');const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw Error('Kein WebGPU-Adapter verfügbar');device=await adapter.requestDevice();Luna.gpu.adapter={vendor:adapter.info?.vendor,architecture:adapter.info?.architecture,device:adapter.info?.device,description:adapter.info?.description};
 device.addEventListener('uncapturederror',e=>{Luna.gpu.errors.push(e.error.message);console.error(e.error.message);Luna.gpu.fallback('WebGPU-Fehler. Ihr Entwurf bleibt gespeichert.')});device.lost.then(info=>{if(Luna.gpu.ready){Luna.gpu.errors.push(info.message||'Device lost');Luna.gpu.fallback('WebGPU-Verbindung unterbrochen. Ihr Entwurf bleibt gespeichert.')}});
 context=$('room').getContext('webgpu');if(!context)throw Error('Kein WebGPU-Zeichenkontext');format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format,alphaMode:'opaque',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});
 const module=device.createShaderModule({code:rasterShader}),shadowModule=device.createShaderModule({code:shadowShader});for(const m of [module,shadowModule]){const info=await m.getCompilationInfo();const errors=info.messages.filter(x=>x.type==='error');if(errors.length)throw Error(errors.map(x=>x.message+' · Zeile '+x.lineNum).join('\n'));}
 const VF=GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,F=GPUShaderStage.FRAGMENT;const layout=device.createBindGroupLayout({entries:[{binding:0,visibility:VF,buffer:{type:'uniform'}},{binding:1,visibility:VF,buffer:{type:'read-only-storage'}},{binding:2,visibility:F,texture:{}},{binding:3,visibility:F,sampler:{}},{binding:4,visibility:F,texture:{}},{binding:6,visibility:F,texture:{viewDimension:'2d-array'}},{binding:7,visibility:F,sampler:{}},{binding:8,visibility:F,buffer:{type:'read-only-storage'}},{binding:9,visibility:F,texture:{sampleType:'depth',viewDimension:'2d-array'}},{binding:10,visibility:F,sampler:{type:'comparison'}},{binding:11,visibility:F,buffer:{type:'uniform'}}]});const pipelineLayout=device.createPipelineLayout({bindGroupLayouts:[layout]});const buffers=[{arrayStride:28,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x3'},{shaderLocation:2,offset:24,format:'uint32'}]}];
 pipeline=await device.createRenderPipelineAsync({layout:pipelineLayout,vertex:{module,entryPoint:'vs',buffers},fragment:{module,entryPoint:'fs',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth24plus',depthWriteEnabled:true,depthCompare:'less'}});
 skyPipeline=await device.createRenderPipelineAsync({layout:pipelineLayout,vertex:{module,entryPoint:'skyVS'},fragment:{module,entryPoint:'skyFS',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list'},depthStencil:{format:'depth24plus',depthWriteEnabled:false,depthCompare:'always'}});
 shadowPipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:shadowModule,entryPoint:'vs',buffers},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less',depthBias:2,depthBiasSlopeScale:1.5}});
 const pm=device.createShaderModule({code:presentShader});presentPipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:pm,entryPoint:'vs'},fragment:{module:pm,entryPoint:'fs',targets:[{format}]},primitive:{topology:'triangle-list'}});
 uniform=device.createBuffer({size:144,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});objectBuffer=device.createBuffer({size:8192*128,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});lightBuffer=device.createBuffer({size:128*32,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});shadowInfoBuffer=device.createBuffer({size:128,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});shadowMap=device.createTexture({size:[1536,1536,2],format:'depth32float',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.RENDER_ATTACHMENT});
 shadowUniforms=[0,1].map(()=>device.createBuffer({size:64,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}));shadowBindGroups=shadowUniforms.map(buffer=>device.createBindGroup({layout:shadowPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:objectBuffer}},{binding:1,resource:{buffer}}]}));
 atlasTexture=device.createTexture({size:[2048,1024],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});device.queue.copyExternalImageToTexture({source:atlas},{texture:atlasTexture},[2048,1024]);materialTexture=device.createTexture({size:[512,512,7],format:'rgba8unorm',mipLevelCount:10,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});makeTextures();textureCanvases.forEach((c,i)=>uploadTextureLayer(c,i));Luna.gpu.sourceTextures=[];
 for(const [layer,asset] of Object.entries(materialAssets)){const image=new Image();image.src=asset.data;await image.decode();const c=document.createElement('canvas');c.width=c.height=512;c.getContext('2d').drawImage(image,0,0,512,512);textureCanvases[Number(layer)]=c;uploadTextureLayer(c,Number(layer));Luna.gpu.sourceTextures.push(asset.name);}
 materialSampler=device.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear',addressModeU:'repeat',addressModeV:'repeat',maxAnisotropy:4});staticEntries=[{binding:0,resource:{buffer:uniform}},{binding:1,resource:{buffer:objectBuffer}},{binding:2,resource:atlasTexture.createView()},{binding:3,resource:device.createSampler({magFilter:'linear',minFilter:'linear'})},{binding:6,resource:materialTexture.createView({dimension:'2d-array'})},{binding:7,resource:materialSampler},{binding:8,resource:{buffer:lightBuffer}},{binding:9,resource:shadowMap.createView({dimension:'2d-array'})},{binding:10,resource:device.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'})},{binding:11,resource:{buffer:shadowInfoBuffer}}];
 await Luna.gpu.loadCustom();Luna.gpu.ready=true;Luna.gpu.backend='WebGPU';Luna.gpu.path='raster-pbr-shadowmaps';Luna.gpu.render(640,360);await Luna.gpu.pending;Luna.gpu.firstGPUMS=performance.now();document.body.classList.remove('fallback');document.body.classList.add('gpu');$('gpu-status').textContent='WebGPU · '+(Luna.gpu.adapter.vendor||'Adapter verfügbar')+' · '+Luna.scene.objects.length+' Formen · PBR & Schattenkarten';Luna.editor.materialThumbs();Luna.gpu.invalidate();
};
