/* Shader strings are inlined by the dependency-free packer. */
const shader=/*ROOM_SHADER*/,presentShader=/*PRESENT_SHADER*/;
const materialAssets=/*MATERIAL_ASSETS*/;
const atlas=document.createElement('canvas');atlas.width=2048;atlas.height=1024;const ag=atlas.getContext('2d');
function drawAtlas(){ag.clearRect(0,0,2048,1024);ag.fillStyle='#fff';ag.font='400 24px Segoe UI, Arial';ag.fillText('F A M I L I E   B E R G E R',90,94);ag.font='300 176px Segoe UI, Arial';ag.fillText('18.740 €',80,274);ag.font='400 48px Segoe UI, Arial';ag.fillText('inkl. 20 % USt · Montage KW38',90,355);ag.fillStyle='#aaa';ag.fillRect(90,397,1390,2);ag.font='400 22px Segoe UI, Arial';ag.fillText('E I N   R A U M .   I H R   Z U H A U S E .',90,451);ag.fillStyle='#fff';ag.font='300 85px Segoe UI, Arial';ag.fillText('31 %',90,686);ag.font='400 36px Segoe UI, Arial';ag.fillText('Marge · intern',90,734)}drawAtlas();
const embeddedStills=/*STILLS*/;
const stillImages=embeddedStills.map((src,i)=>{const im=new Image();im.onload=()=>{if(!Luna.gpu.ready&&i===Luna.cam.chapter){Luna.gpu.drawStill?.($('still'));Luna.gpu.firstImageMS??=performance.now()}const canvas=$('filmstrip').children[i]?.querySelector('canvas');if(canvas)Luna.gpu.drawStill(canvas,i)};im.src=src;return im});
Luna.gpu.drawStill=(canvas,chapter=Luna.cam.chapter)=>{const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,im=stillImages[chapter];if(im?.complete&&im.naturalWidth){const scale=Math.max(w/im.naturalWidth,h/im.naturalHeight),iw=im.naturalWidth*scale,ih=im.naturalHeight*scale;g.drawImage(im,(w-iw)/2,(h-ih)/2,iw,ih);Luna.gpu.firstImageMS??=performance.now();}else{const im2=stillImages.find(im=>im.complete&&im.naturalWidth);if(im2)g.drawImage(im2,0,0,w,h);else{g.fillStyle='#8b8679';g.fillRect(0,0,w,h);g.fillStyle='#3b4243';g.beginPath();g.moveTo(0,h*.73);g.lineTo(w*.66,h*.44);g.lineTo(w,h*.62);g.lineTo(w,h);g.lineTo(0,h);g.fill();g.fillStyle='#ae9673';g.fillRect(w*.34,h*.36,w*.44,h*.26);g.fillStyle='#c6baa2';g.fillRect(w*.31,h*.57,w*.36,h*.042);g.fillStyle='#8e795b';g.fillRect(w*.33,h*.61,w*.30,h*.17)}}};
function resizeStill(){const c=$('still'),ratio=Math.min(1.25,devicePixelRatio);c.width=Math.round(innerWidth*ratio);c.height=Math.round(innerHeight*ratio);Luna.gpu.drawStill(c)}
Luna.gpu.invalidate=()=>{dirty=true;settleAt=performance.now();if(!Luna.gpu.ready)Luna.gpu.drawStill($('still'));if(!raf)raf=requestAnimationFrame(tick)};
function kelvinRGB(k){const t=k/100;const r=t<=66?255:329.698727446*Math.pow(t-60,-.1332047592);const g=t<=66?99.4708025861*Math.log(t)-161.1195681661:288.1221695283*Math.pow(t-60,-.0755148492);const b=t>=66?255:t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307;return [r,g,b].map(x=>Math.pow(clamp(x/255),1.35))}
Luna.gpu.render=(width,height)=>{
if(!Luna.gpu.ready)return;uploadScene();const c=$('room');let w=width,h=height;
if(!w||!h){const moving=Luna.cam.playing||!!Luna.cam.transition||performance.now()-settleAt<150;let ratio=Math.min(devicePixelRatio,1.15,1920/innerWidth);if(moving)ratio=Math.min(.7,1160/innerWidth);w=Math.max(2,Math.round(innerWidth*ratio));h=Math.max(2,Math.round(innerHeight*ratio))}
if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;
if(historySize!==w+'x'+h){for(const t of histories)t.destroy();histories=[0,1].map(()=>device.createTexture({size:[w,h],format:'rgba16float',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.RENDER_ATTACHMENT}));groupsGPU=histories.map(t=>device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[...staticEntries,{binding:4,resource:t.createView()}]}));presentGroups=histories.map(t=>device.createBindGroup({layout:presentPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:t.createView()}]}));historySize=w+'x'+h;sampleCount=0;stateKey='';}
const b=Luna.cam.basis(),s=Luna.scene,selected=Luna.editor.open?groups.findIndex(g=>g.id===Luna.editor.selected):-1;
const key=[w,h,...Luna.cam.eye,...Luna.cam.to,Luna.cam.fov,s.sun,s.kelvin,s.power,s.exposure,s.strip,s.price,s.ceo,s.revision,selected,Luna.editor.open].join('|');if(key!==stateKey){sampleCount=0;stateKey=key}
const read=sampleCount%2,write=1-read;const values=new Float32Array([...Luna.cam.eye,b.tan*w/h,...b.f,b.tan,...b.r,0,...b.u,0,w,h,s.sun,s.material,s.price?1:0,s.ceo?1:0,Luna.cam.chapter,sampleCount,...kelvinRGB(s.kelvin),s.power,s.exposure,s.strip?1:0,0,Luna.editor.open?1:0,lightData.length,selected,sortedObjects.length,bvhNodes.length]);device.queue.writeBuffer(uniform,0,values);
const enc=device.createCommandEncoder(),pass=enc.beginRenderPass({colorAttachments:[{view:histories[write].createView(),loadOp:'clear',storeOp:'store'}]});pass.setPipeline(pipeline);pass.setBindGroup(0,groupsGPU[read]);pass.draw(3);pass.end();lastSurface=context.getCurrentTexture();const display=enc.beginRenderPass({colorAttachments:[{view:lastSurface.createView(),loadOp:'clear',storeOp:'store'}]});display.setPipeline(presentPipeline);display.setBindGroup(0,presentGroups[write]);display.draw(3);display.end();device.queue.submit([enc.finish()]);sampleCount++;Luna.gpu.samples=sampleCount;Luna.gpu.frames++;gpuInFlight=true;Luna.gpu.pending=device.queue.onSubmittedWorkDone().then(()=>{gpuInFlight=false});
};
Luna.gpu.init=async()=>{
if(forcedFallback)throw Error('Canvas2D ausdrücklich gewählt');if(!navigator.gpu)throw Error('Dieser Browser stellt WebGPU nicht bereit');
const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw Error('Kein WebGPU-Adapter verfügbar');device=await adapter.requestDevice();Luna.gpu.adapter={vendor:adapter.info?.vendor,architecture:adapter.info?.architecture,device:adapter.info?.device,description:adapter.info?.description};
device.addEventListener('uncapturederror',e=>{Luna.gpu.errors.push(e.error.message);console.error(e.error.message);Luna.gpu.fallback('WebGPU-Fehler. Ihr Entwurf bleibt gespeichert.')});device.lost.then(info=>{if(Luna.gpu.ready){Luna.gpu.errors.push(info.message||'Device lost');Luna.gpu.fallback('WebGPU-Verbindung unterbrochen. Ihr Entwurf bleibt gespeichert.')}});
context=$('room').getContext('webgpu');if(!context)throw Error('Kein WebGPU-Zeichenkontext');format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format,alphaMode:'opaque',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});
const module=device.createShaderModule({code:shader});const diagnostics=await module.getCompilationInfo();const errors=diagnostics.messages.filter(m=>m.type==='error');if(errors.length)throw Error(errors.map(m=>m.message+' · Zeile '+m.lineNum).join('\n'));
pipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list'}});const pm=device.createShaderModule({code:presentShader});presentPipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:pm,entryPoint:'vs'},fragment:{module:pm,entryPoint:'fs',targets:[{format}]},primitive:{topology:'triangle-list'}});
uniform=device.createBuffer({size:144,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});objectBuffer=device.createBuffer({size:8192*128,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});nodeBuffer=device.createBuffer({size:8192*32,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});lightBuffer=device.createBuffer({size:128*32,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});
atlasTexture=device.createTexture({size:[2048,1024],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});device.queue.copyExternalImageToTexture({source:atlas},{texture:atlasTexture},[2048,1024]);
materialTexture=device.createTexture({size:[512,512,7],format:'rgba8unorm',mipLevelCount:10,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});makeTextures();textureCanvases.forEach((c,i)=>uploadTextureLayer(c,i));Luna.gpu.sourceTextures=[];for(const [layer,asset] of Object.entries(materialAssets)){const im=new Image();im.src=asset.data;await im.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=512;canvas.getContext('2d').drawImage(im,0,0,512,512);textureCanvases[Number(layer)]=canvas;uploadTextureLayer(canvas,Number(layer));Luna.gpu.sourceTextures.push(asset.name)}materialSampler=device.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear',addressModeU:'repeat',addressModeV:'repeat',maxAnisotropy:4});
staticEntries=[{binding:0,resource:{buffer:uniform}},{binding:1,resource:{buffer:objectBuffer}},{binding:2,resource:atlasTexture.createView()},{binding:3,resource:device.createSampler({magFilter:'linear',minFilter:'linear'})},{binding:5,resource:{buffer:nodeBuffer}},{binding:6,resource:materialTexture.createView({dimension:'2d-array'})},{binding:7,resource:materialSampler},{binding:8,resource:{buffer:lightBuffer}}];
await Luna.gpu.loadCustom();Luna.gpu.ready=true;Luna.gpu.backend='WebGPU';Luna.gpu.render();await Luna.gpu.pending;Luna.gpu.firstGPUMS=performance.now();document.body.classList.remove('fallback');document.body.classList.add('gpu');$('gpu-status').textContent='WebGPU · '+(Luna.gpu.adapter.vendor||'Adapter verfügbar')+' · '+Luna.scene.objects.length+' Formen · beschleunigte Strahlverfolgung';Luna.editor.materialThumbs();Luna.gpu.invalidate();
};
Luna.gpu.fallback=reason=>{Luna.gpu.ready=false;Luna.gpu.backend='Canvas2D';Luna.gpu.reason=reason;Luna.cam.playing=false;document.body.classList.remove('gpu');document.body.classList.add('fallback');$('fallback-note').textContent='STANDBILDER DER AUSGANGSKÜCHE · '+reason+' Eigene Entwürfe und Live-Gestaltung benötigen WebGPU.';if(Luna.editor.open)Luna.editor.toggle(false);for(let i=0;i<6;i++)Luna.gpu.drawStill($('filmstrip').children[i].querySelector('canvas'),i);Luna.gpu.drawStill($('still'));Luna.hud.sync()};
Luna.gpu.settle=async(w=1920,h=1080,n=48)=>{if(!Luna.gpu.ready)throw Error('WebGPU ist nicht verfügbar');busy=true;try{await Luna.gpu.pending;for(let i=0;i<n;i++){Luna.gpu.render(w,h);await Luna.gpu.pending;}Luna.hud.draw();return Luna.gpu.samples}finally{busy=false;Luna.gpu.invalidate()}};
Luna.gpu.readPixels=async(w=1920,h=1080,n=48)=>{if(!Luna.gpu.ready)throw Error('WebGPU ist nicht verfügbar');busy=true;try{await Luna.gpu.pending;for(let i=0;i<n;i++){Luna.gpu.render(w,h);await Luna.gpu.pending;}const pitch=Math.ceil(w*4/256)*256,buf=device.createBuffer({size:pitch*h,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const enc=device.createCommandEncoder();enc.copyTextureToBuffer({texture:lastSurface},{buffer:buf,bytesPerRow:pitch,rowsPerImage:h},[w,h]);device.queue.submit([enc.finish()]);await buf.mapAsync(GPUMapMode.READ);const raw=new Uint8Array(buf.getMappedRange()),data=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)data.set(raw.subarray(y*pitch,y*pitch+w*4),y*w*4);if(format.startsWith('bgra'))for(let i=0;i<data.length;i+=4){const t=data[i];data[i]=data[i+2];data[i+2]=t}buf.unmap();buf.destroy();return new ImageData(data,w,h)}finally{busy=false;Luna.gpu.invalidate()}};
function tick(t){raf=0;const dt=lastFrame?Math.min(.20,(t-lastFrame)/1000):0;lastFrame=t;let changed=false;
if(!busy&&Luna.cam.playing&&!document.hidden){Luna.cam.time=Math.min(48,Luna.cam.time+dt);const chapter=Math.min(5,Math.floor(Luna.cam.time/8));Luna.cam.chapter=chapter;Luna.cam.apply(chapter,(Luna.cam.time-chapter*8)/8);if(Luna.cam.time>=48)Luna.cam.playing=false;Luna.hud.sync();changed=true;}
if(!busy&&Luna.cam.transition){const tr=Luna.cam.transition,phase=clamp((t-tr.start)/900),target=cs[Luna.cam.chapter];const ph=Luna.cam.chapter===3?.5:.20;const eye=V.lerp(target.eye,target.end,smooth(ph));Luna.cam.eye=V.lerp(tr.old.eye,eye,smooth(phase));Luna.cam.to=V.lerp(tr.old.to,target.to,smooth(phase));Luna.cam.fov=mix(tr.old.fov,target.fov,smooth(phase));Luna.scene.sun=mix(tr.old.sun,target.sun,smooth(phase));if(phase>=1)Luna.cam.transition=null;changed=true;}
const targetSamples=Luna.scene.quality==='high'?80:48;
if(!busy){if(Luna.gpu.ready){if(!gpuInFlight&&(dirty||changed||sampleCount<targetSamples||performance.now()-settleAt<200)){Luna.gpu.render();dirty=false;}}else if(changed||dirty){Luna.gpu.drawStill($('still'));dirty=false}Luna.hud.draw();}
if(Luna.cam.playing||Luna.cam.transition||gpuInFlight||dirty||Luna.gpu.ready&&sampleCount<targetSamples||performance.now()-settleAt<230)raf=requestAnimationFrame(tick);
}
